map_update_interval: 2.0
maxUrange: 30.0

sigma: 0.05 # The sigma used by the greedy endpoint matching
kernelSize: 1 # The kernel in which to look for a correspondence
lstep: 0.05 # The optimization step in translation
astep: 0.05 # The optimization step in rotation
iterations: 5 # The number of iterations of the scanmatcher

lsigma: 0.01 # The sigma of a beam used for likelihood computation
ogain: 1.0 # Gain to be used while evaluating the likelihood, for smoothing the resampling effects

lskip: 4 # Number of beams to skip in each scan. Take only every (n+1)th laser ray for computing a match (0 = take all rays)
minimumScore: 50 # Minimum score for considering the outcome of the scan matching good. Can avoid jumping pose estimates in large open spaces when using laser scanners with limited range (e.g. 5m). Scores go up to 600+, try 50 for example when experiencing jumping estimate issues.

srr: 0.1 # Odometry error in translation as a function of translation (rho/rho)
srt: 0.2 # Odometry error in translation as a function of rotation (rho/theta)
str: 0.1 # Odometry error in rotation as a function of translation (theta/rho)
stt: 0.2 # Odometry error in rotation as a function of rotation (theta/theta)

linearUpdate: 1.0 # Process a scan each time the robot translates this far
angularUpdate: 0.5 # Process a scan each time the robot rotates this far
temporalUpdate: -1.0 # Process a scan if the last scan processed is older than the update time in seconds. A value less than zero will turn time based updates off.

resampleThreshold: 0.5 # The Neff based resampling threshold
particles: 100 # Number of particles in the filter
xmin: -150.0
ymin: -50.0
xmax: 50.0
ymax: 50.0
delta: 0.05

llsamplerange: 0.01 # Translational sampling range for the likelihood
llsamplestep: 0.01 # Translational sampling step for the likelihood
lasamplerange: 0.005 # Angular sampling range for the likelihood
lasamplestep: 0.005 # Angular sampling step for the likelihood
